<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Job represents a single job
 *
 * Generated from protobuf message <code>proto.Job</code>
 */
class Job extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     */
    protected $unique_id = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated uint32 dependson = 4;</code>
     */
    private $dependson;
    /**
     * Generated from protobuf field <code>repeated .proto.Argument args = 5;</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>.proto.ManualInteraction interaction = 6;</code>
     */
    protected $interaction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $unique_id
     *     @type string $title
     *     @type string $description
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $dependson
     *     @type \Proto\Argument[]|\Google\Protobuf\Internal\RepeatedField $args
     *     @type \Proto\ManualInteraction $interaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plugin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     * @return int
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueId($var)
    {
        GPBUtil::checkUint32($var);
        $this->unique_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 dependson = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDependson()
    {
        return $this->dependson;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 dependson = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDependson($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->dependson = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Argument args = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Argument args = 5;</code>
     * @param \Proto\Argument[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Argument::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.ManualInteraction interaction = 6;</code>
     * @return \Proto\ManualInteraction
     */
    public function getInteraction()
    {
        return $this->interaction;
    }

    /**
     * Generated from protobuf field <code>.proto.ManualInteraction interaction = 6;</code>
     * @param \Proto\ManualInteraction $var
     * @return $this
     */
    public function setInteraction($var)
    {
        GPBUtil::checkMessage($var, \Proto\ManualInteraction::class);
        $this->interaction = $var;

        return $this;
    }

}

