<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * JobResult represents the result of an executed job
 *
 * Generated from protobuf message <code>proto.JobResult</code>
 */
class JobResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     */
    protected $unique_id = 0;
    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     */
    protected $failed = false;
    /**
     * Generated from protobuf field <code>bool exit_pipeline = 3;</code>
     */
    protected $exit_pipeline = false;
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $unique_id
     *     @type bool $failed
     *     @type bool $exit_pipeline
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plugin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     * @return int
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * Generated from protobuf field <code>uint32 unique_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueId($var)
    {
        GPBUtil::checkUint32($var);
        $this->unique_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     * @return bool
     */
    public function getFailed()
    {
        return $this->failed;
    }

    /**
     * Generated from protobuf field <code>bool failed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailed($var)
    {
        GPBUtil::checkBool($var);
        $this->failed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exit_pipeline = 3;</code>
     * @return bool
     */
    public function getExitPipeline()
    {
        return $this->exit_pipeline;
    }

    /**
     * Generated from protobuf field <code>bool exit_pipeline = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setExitPipeline($var)
    {
        GPBUtil::checkBool($var);
        $this->exit_pipeline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

